---
scouts:
  - scout1
  - scout2
  - scout3
  - scout4
  - scout5
  - scout6
  - scout7
  - scout8
  - scout9
  - scout10
  - scout11
  - scout12
  - scout13
  - scout14
  - scout15
  - scout16
  - scout17
  - scout18
  - scout19
  - scout20
