---
- name: Install PHP 7.0
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: "remi-php70"
  with_items:
  - php
  - php-cli
  - php-common
  - php-devel
  - php-fpm
  - php-gd
  - php-imap
  - php-ldap
  - php-mbstring
  - php-opcache
  - php-pdo
  - php-pear
  - php-pecl-apcu
  - php-xml
  - php-xmlrpc

- name: Start php-fpm service
  service:
    name: php-fpm
    state: started
    enabled: true
